// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ruibxxcvkxameijxdfke.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ1aWJ4eGN2a3hhbWVpanhkZmtlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1NDY0ODgsImV4cCI6MjA3NDEyMjQ4OH0.w3zYVYcOGq7L24lywWcIu-Q8Kf6ZsrABudXUE5VjgEA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});